feat: add timeout option for the content client
amplience/dc-delivery-sdk-js pull request #34
Opened 2021-02-17 11:39 UTC by rs-amp

This PR adds a timeout in milliseconds that can be given to the content client, which it passes to the http client. It defaults to 0 (infinite) to match the current behaviour.

When the timeout is reached, the axios http client will throw an error and interrupt the request.

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests (`npm run test`) for the changes have been added (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Docs (`npm run doc`) have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] PR title and git commit messages conform to the [conventionalcommits](https://www.conventionalcommits.org/en/v1.0.0/) specification

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?
Requests have no timeout, so can take an unbounded amount of time to succeed or fail.

## What is the new behavior?
When a timeout is specified, requests will fail after the timeout period has been reached.

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

None.

2021-02-18 17:00 UTC, pixelscript approved these changes

2021-02-18 17:10 UTC, pixelscript reviewed
Should update the config options table in the README.md

2021-02-18 17:18 UTC, srweeks approved these changes

2021-02-19 08:33 UTC, Benj0s approved these changes

2021-02-19 09:24 UTC, PikinerLiliya approved these changes

2021-02-19 12:11 UTC, easen-amp approved these changes

2021-02-19 12:12 UTC, easen-amp requested changes
Can the README be updated to include this new option

2021-02-19 16:10 UTC, rs-amp commented
Added the option to the readme.

2021-02-22 15:28 UTC, easen-amp approved these changes

2021-02-23 16:48 UTC, merged